# This workflow will build the project and deploy it to Google App Engine Standard when a release is created

name: Deploy to the production environment's Google App Engine Standard

on:
  release:
    types: [created]

# Environment variables available to all jobs and steps in this workflow
env:
  COOKIE_SESSION_KEY: ${{ secrets.PROD_COOKIE_SESSION_KEY }}
  DISCORD_BOT_SECRET: ${{ secrets.PROD_DISCORD_BOT_SECRET }}
  DISCORD_CLIENT_ID: ${{ secrets.PROD_DISCORD_CLIENT_ID }}
  DISCORD_CLIENT_SECRET: ${{ secrets.PROD_DISCORD_CLIENT_SECRET }}
  DISCORD_GUILD: 'caravan-clubs'
  DISCORD_GUILD_ID: '592761082523680798'
  DISCORD_REDIRECT: 'https://caravanapp.ca/api/auth/discord/callback'
  GAE_ENV: 'production'
  GCLOUD_PROJECT: ${{ secrets.PROD_GCLOUD_PROJECT }}
  GITHUB_SHA: ${{ github.sha }}
  MONGO_DB: ${{ secrets.PROD_MONGO_DB }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup-build-deploy:
    name: Setup, Build, and Deploy to prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.PROD_GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.PROD_GOOGLE_SERVICE_ACCOUNT_KEY }}

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command

      # Deploy the code to the Google App Engine Standard
      - name: Deploy
        run: |
          yarn create-env
          gcloud config set core/project $GCLOUD_PROJECT
          gcloud app deploy app.production.yaml --promote
